---
title: "my_website"
---

# Junwei Chen

## About Me
Welcome! I'm Junwei Chen, an aspiring Actuarial Scientist with a solid foundation in mathematics, statistics, and financial principles, currently completing my BSc in Actuarial Science at the University of Toronto. My academic journey is driven by a passion for applying mathematical and statistical methods to solve problems in finance and insurance, equipped with a strong proficiency in R and Microsoft Office.

## Volunteer Experience
In March and April of 2018, I had the privilege of volunteering at Huamei Kindergarten in Guangzhou, China. My responsibilities included organizing extracurricular activities and ensuring the safety of the children. This experience was profoundly rewarding, allowing me to give back to my community and develop valuable organizational and leadership skills.

## Hobbies
When I'm not immersed in my studies or volunteering, I enjoy playing badminton. This sport not only helps me stay physically active but also offers a fantastic way to unwind and keep my mind sharp.

## Computer Skills
Software Skills: Proficient in R, which is essential for data analysis and statistical modeling in my field of study. Additionally, I am skilled in Microsoft Office, enabling me to effectively communicate and present my findings.
Contact Me
For collaborations, opportunities, or just to say hello, feel free to reach out to me:

Email: junwei.chen@gmail.com

See my [CV](./cv.pdf) for more details.
